//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &quot;fake-class.h&quot;
        ///
        ///FakeClass::FakeClass() : a(42) {}
        ///.
        /// </summary>
        internal static string fake_class_cpp {
            get {
                return ResourceManager.GetString("fake_class_cpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class OpaqueClass;
        ///
        ///struct FakeClass {
        ///    int a;
        ///    OpaqueClass *p;
        ///    FakeClass();
        ///};.
        /// </summary>
        internal static string fake_class_h {
            get {
                return ResourceManager.GetString("fake_class_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &lt;iostream&gt;
        ///#include &quot;fake-class.h&quot;
        ///
        ///int main() {
        ///    FakeClass i;
        ///    std::cout &lt;&lt; i.a &lt;&lt; std::endl;
        ///    int a;
        ///};
        ///.
        /// </summary>
        internal static string fake_main_cpp {
            get {
                return ResourceManager.GetString("fake_main_cpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &quot;quoted-header.h&quot;
        ///#include &lt;angle-bracketed-header&gt;
        ///
        ///#define MACRO(a,b,c) (a + b * c)
        ///#define CONSTANT 42
        ///
        ///// Line comment
        ///
        ////* Paragraph comment
        ///
        ///*/
        ///
        ///namespace {
        ///	const int foo = 123;
        ///}
        ///
        ///class ClassOne {
        ///	int a;
        ///	int b;
        ///
        ///private:
        ///
        ///public:
        ///	ClassOne(int a, int b) :
        ///		a(a),
        ///		b(b) { 
        ///			a = b;
        ///	}
        ///}
        ///
        ///// namespace parentnamespace {
        ///namespace test {
        ///
        ///
        ///	/**
        ///	  * Class is documented.
        ///	  */
        ///	class ClassTwo {
        ///
        ///		// Method explanation
        ///		char *GetStuff const(int arg1, c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string kitchen_sink {
            get {
                return ResourceManager.GetString("kitchen_sink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class OpaqueClass {
        ///    int a,b,c;
        ///}.
        /// </summary>
        internal static string opaque_class_h {
            get {
                return ResourceManager.GetString("opaque_class_h", resourceCulture);
            }
        }
    }
}
